Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -41,15 +41,14 @@ jobs:
           REMOTE_HOST: ${{ secrets.HOST_DNS }}
           REMOTE_USER: ${{ secrets.USERNAME }}
           TARGET: ${{ secrets.TARGET_DIR }}
-        with:
-          script: |
-            # SSH command to connect to the server and execute commands
-            ssh -i "$SSH_PRIVATE_KEY" "$REMOTE_USER@$REMOTE_HOST" "rm -rf $TARGET/* && exit" 
-            SSH_EXIT_CODE=$?
-            if [ $SSH_EXIT_CODE -ne 0 ]; then
-              echo "SSH command failed with exit code $SSH_EXIT_CODE"
-              exit $SSH_EXIT_CODE
-            fi
+        run: |
+          # SSH command to connect to the server and execute commands
+          ssh -i "$SSH_PRIVATE_KEY" "$REMOTE_USER@$REMOTE_HOST" "rm -rf $TARGET/* && exit" 
+          SSH_EXIT_CODE=$?
+          if [ $SSH_EXIT_CODE -ne 0 ]; then
+            echo "SSH command failed with exit code $SSH_EXIT_CODE"
+            exit $SSH_EXIT_CODE
+          fi
 
-            # SCP command to copy files to the server
-            scp -i "$SSH_PRIVATE_KEY" /local/path/file.txt "$REMOTE_USER@$REMOTE_HOST:$TARGET/"
+          # SCP command to copy files to the server
+          scp -i "$SSH_PRIVATE_KEY" /local/path/file.txt "$REMOTE_USER@$REMOTE_HOST:$TARGET/"
